server:
  port: 9081

#该应用的特有属性全部写在这里
wallet:
  gateway: https://openapi.wallet-dev.com
  withdraw-to-any-wallet : /wallet-trade-merchant/v1/pay/blockchain/create
  withdraw-to-any-wallet-by-custom-rate : /wallet-trade-merchant/v1/pay/blockchain/custom/rate/create


